name: Publish

on:
  push:
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Set up Deno
        uses: denoland/setup-deno@v2.0.1
      - run: deno publish
