name: Test

on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Deno
        uses: denoland/setup-deno@v2.0.1
      - run: deno fmt --check
      - run: deno lint
      - run: |
          deno test --frozen --coverage --doc
          deno coverage --lcov > ./coverage/cov.lcov
      - run: deno coverage
      - name: Push the coverage report to Codecov
        uses: codecov/codecov-action@v5.0.7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/cov.lcov
      - run: deno publish --dry-run
