name: Test

on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Deno
        uses: denoland/setup-deno@v1.5.1
      - run: deno fmt --check
      - run: deno lint
      - run: |
          deno test --frozen --coverage --doc
          deno coverage --lcov > ./coverage/cov.lcov
      - run: deno coverage
      - uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/cov.lcov
      - run: deno publish --dry-run
